# Generated by Django 4.0.6 on 2022-11-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Auther',
        ),
    ]
